-- Checking Data imported successfully or No
select count(*) from customer;

select * from customer limit 20;

-- Answering Questions

-- Q1 What is the total revenue generated by male vs female customers?

select gender,sum(purchase_amount) as revenue_generated from customer
group by 1 order by 1;

-- Q2 Which Customers used a discount but still spent more than average purchase amount?
select customer_id,purchase_amount from customer where
discount_applied='Yes' and
purchase_amount > (select avg(purchase_amount) from customer);

-- Q3 Which are the top 5 products with the higest average review rating?

select item_purchased,ROUND(CAST(avg(review_rating) as numeric),2) as avg_review_rating 
from customer group by 1 order by 2 desc limit 5;

-- Q4 Compare the average Purchase Amounts between Standard and Express Shipping

select item_purchased,shipping_type, round(cast(avg(purchase_amount)as numeric),2) as avg_purchase_amt
from customer where shipping_type in ('Express','Standard') 
group by 1,2 order by 1,2;

-- Q5 Do subscribed customers spend more? Compare average spend and total revenue between subscribed and non subscribed customers

select subscription_status,count(customer_id) as total_customers,round(cast(avg(purchase_amount)as numeric),2) as avg_purchase_amt,round(cast(sum(purchase_amount)as numeric),2) as total_purchase_amt
from customer group by 1 order by 1;

-- Q6 Which  products have the highest perdentage of purchases with discounts applied?
select a.item_purchased, 
count(*) as item_purchased_on_discount,
(select count(*) from customer b where b.item_purchased=a.item_purchased) as total_purchases,
round((count(*) *100)/(select count(*) from customer b where b.item_purchased=a.item_purchased),2) as percent
from customer a where discount_applied='Yes'
group by 1 order by 4 desc limit 5;


-- Q7 Segment customers into New, Returning and Loyal based on their total number of previous purchases, and show count of each segment?
with customer_type as
(
select customer_id, previous_purchases,
CASE 
	when previous_purchases=1 then 'New'
	when previous_purchases between 1 and 10 then 'Returning'
	else 'Loyal'
end as customer_segment
from customer
)
select customer_segment,count(*) from customer_type
group by 1;

-- Q8 What are the top 3 most purchased products within each category?
with cte as
(
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as most_purchased
from customer
group by 1,2
)
select category,item_purchased,total_orders from cte where most_purchased<4;

-- Q9 Are customers who are repeat buyers(more than 5 prev purchases) also likely to subscribe
select subscription_status, count(customer_id) as repeat_buyers
from customer where previous_purchases>=5 group by 1;

-- Q10 What is the revenue contribution of each age group
select age_group,sum(purchase_amount) as revenue_contribution
from customer group by 1 order by 2 desc;